# Generated by Django 2.2.5 on 2019-09-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0004_auto_20180214_0617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="package.Category",
                verbose_name="Installation",
            ),
        ),
    ]
