# Generated by Django 2.2.13 on 2020-06-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_auto_20190927_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Rank'),
        ),
    ]
