# Generated by Django 3.2.7 on 2021-09-29 09:43

from django.db import migrations

def migrate_license(apps, schema_editor):
    """
    Migrate license from charfield to ArrayField.
    This migration copies data from the old license column to the new
    licenses column which is a ArrayField.
    """
    Version = apps.get_model("package", "Version")
    for version in Version.objects.filter(license__isnull=False):
        if version.license:
            version.licenses = version.license.split(',')
            version.save()

class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_auto_20210929_0942'),
    ]

    operations = [
        migrations.RunPython(migrate_license),
    ]
