# Generated by Django 3.2.7 on 2021-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0010_auto_20210929_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="date_repo_archived",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date when repo was archived"
            ),
        ),
    ]
