# Generated by Django 4.0.2 on 2022-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_auto_20210929_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='commit_list',
            field=models.TextField(blank=True, max_length=500, verbose_name='Commit List'),
        ),
        migrations.AlterField(
            model_name='package',
            name='participants',
            field=models.TextField(blank=True, help_text='List of collaborats/participants on the project', max_length=500, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='package',
            name='repo_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Repo Description'),
        ),
    ]
