# Generated by Django 4.0.2 on 2022-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_alter_category_description_alter_package_commit_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='commit_list',
            field=models.TextField(blank=True, verbose_name='Commit List'),
        ),
        migrations.AlterField(
            model_name='package',
            name='participants',
            field=models.TextField(blank=True, help_text='List of collaborats/participants on the project', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='package',
            name='repo_description',
            field=models.TextField(blank=True, verbose_name='Repo Description'),
        ),
    ]
