# Generated by Django 4.0.3 on 2022-03-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_package_date_repo_archived'),
        ('package', '0012_alter_category_description_alter_package_commit_list_and_more'),
    ]

    operations = [
    ]
