# Generated by Django 4.0.3 on 2022-03-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0012_alter_package_repo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="last_exception",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="last_exception_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="last_exception_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
