# Generated by Django 4.0.3 on 2022-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_merge_20220306_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='repo_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Repo Description'),
        ),
    ]
