# Generated by Django 4.0.3 on 2022-03-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0014_package_markers_alter_package_pypi_classifiers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="deprecates_package",
            field=models.ForeignKey(
                blank=True,
                help_text="The Package that replaces *this* Package",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement",
                to="package.package",
            ),
        ),
    ]
