# Generated by Django 4.0.3 on 2022-05-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_flaggedpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='package.package'),
        ),
    ]
