# Generated by Django 5.0.3 on 2024-03-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_alter_package_pypi_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Enter your project repo hosting URL here. Example: https://github.com/djangopackages/djangopackages', unique=True, verbose_name='repo URL'),
        ),
    ]
