# Generated by Django 5.0.6 on 2024-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0020_alter_package_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='favorite_count',
            field=models.IntegerField(default=0, help_text='Favorite count', verbose_name='Favorite'),
        ),
    ]
