# Generated by Django 5.2.9 on 2026-01-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0023_alter_category_id_alter_commit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='commit_count',
            field=models.IntegerField(default=0, verbose_name='Commit Count'),
        ),
        migrations.AddField(
            model_name='package',
            name='commits_over_52w',
            field=models.JSONField(default=list, verbose_name='Commit List Over 52 Weeks'),
        ),
        migrations.AddField(
            model_name='package',
            name='last_commit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_version_package', to='package.version'),
        ),
    ]
