# Generated by Django 5.2.8 on 2026-01-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0023_alter_category_id_alter_commit_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='commit_list',
        ),
        migrations.RemoveField(
            model_name='package',
            name='markers',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pypi_info',
        ),
        migrations.AddField(
            model_name='package',
            name='commits_over_52',
            field=models.TextField(blank=True, verbose_name='Commit List Over 52 Weeks'),
        ),
        migrations.AddField(
            model_name='package',
            name='last_commit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_version_package', to='package.version'),
        ),
    ]
