# Generated by Django 5.2.9 on 2026-01-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0024_package_commit_count_package_commits_over_52w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='commit_list',
        ),
    ]
