# Generated by Django 5.2.11 on 2026-02-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0025_remove_package_commit_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
