# Generated by Django 6.0.4 on 2026-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0026_delete_commit"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("package", "number"), name="unique_version_package_number"
            ),
        ),
    ]
