# Generated by Django 6.0.4 on 2026-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0027_version_unique_version_package_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='documentation_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Documentation URL'),
        ),
    ]
