# Generated by Django 5.2.11 on 2026-02-20 11:02

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(help_text='Admin-facing label for this banner.', max_length=200, verbose_name='title')),
                ('content', models.TextField(help_text='Banner body text. HTML is supported.', verbose_name='content')),
                ('banner_type', models.CharField(choices=[('sponsored', 'Sponsored'), ('notice', 'Notice'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='notice', help_text='Determines the visual style of the banner.', max_length=20, verbose_name='banner type')),
                ('start_date', models.DateTimeField(help_text='When the banner becomes visible.', verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the banner expires. Leave blank for indefinite display.', null=True, verbose_name='end date')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Whether users can dismiss this banner.', verbose_name='dismissible')),
                ('icon', models.CharField(blank=True, help_text="Phosphor icon class override (e.g. 'ph-megaphone'). Leave blank to use the default icon for the banner type.", max_length=100, verbose_name='icon override')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Horizontal alignment of the banner content.', max_length=10, verbose_name='content alignment')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['-created'],
            },
        ),
    ]
