# Generated by Django 5.0.3 on 2024-03-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180214_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_code_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitLab account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_account',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='GitHub account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='GitHub account'),
        ),
    ]
