# Generated by Django 4.2.9 on 2024-04-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('profiles', '0005_extrafields_squashed_0009_profile_extra_field_content_01_and_more'), ('profiles', '0010_alter_profile_extra_field_content_01_and_more'), ('profiles', '0011_remove_profile_extra_field_content_01_and_more'), ('profiles', '0012_alter_extrafields_options'), ('profiles', '0013_alter_extrafields_key_alter_extrafields_value')]

    dependencies = [
        ('profiles', '0004_remove_profile_google_code_url_profile_gitlab_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Extra Field',
                'verbose_name_plural': 'Extra Fields',
            },
        ),
    ]
