# Generated by Django 4.2.9 on 2024-03-29 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_remove_profile_google_code_url_profile_gitlab_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_field_content_01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 01'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_content_02',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 02'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_content_03',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 03'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_content_04',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 04'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_label_01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 01'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_label_02',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 02'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_label_03',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 03'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_field_label_04',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra field label 04'),
        ),
    ]
