# Generated by Django 6.0.4 on 2026-09-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_share_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trusted_override',
            field=models.BooleanField(default=False, help_text='Skip the new-account review period for this user', verbose_name='Trusted'),
        ),
    ]
