# Generated by Django 4.2.9 on 2024-03-29 19:26

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_extra_field_content_01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_content_01',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_content_02',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_content_03',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_content_04',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_label_01',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_label_02',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_label_03',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_field_label_04',
        ),
        migrations.CreateModel(
            name='ExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
