# Generated by Django 4.2.9 on 2024-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_extra_field_content_01_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrafields',
            options={'verbose_name': 'Extra Field', 'verbose_name_plural': 'Extra Fields'},
        ),
    ]
