# Generated by Django 4.2.9 on 2024-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_extrafields_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='value',
            field=models.CharField(max_length=256),
        ),
    ]
