# TODO: address
#
# - https://github.blog/2020-03-24-getting-started-with-github-sponsors/
# - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# community_bridge:   community_bridge_username
# custom:             ["custom_url.com", "another_custom_url.com"]
# github:             [github_username]
# issuehunt:          issuehunt_username
# ko_fi:              ko_fi_username
# liberapay:          liberapay_username
# open_collective:    open_collective_username
# otechie:            otechie_username
# patreon:            patreon_username
# tidelift:           tidelift_package_name
