version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=djangopackages

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=djangopackages
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
    env_file:
      - .env.local

  redis:
    build: ./compose/redis
