version: '3.2'

volumes:
  static: {}
  media: {}

services:
  django-a:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    user: django
    depends_on:
      # - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "5"
        # compress: "true"

  django-b:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    user: django
    depends_on:
      # - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "5"
        # compress: "true"

  # postgres:
  #   build: ./dockerfiles/postgres
  #   volumes:
  #     - /data/djangopackages/postgres:/var/lib/postgresql/data
  #     - /data/djangopackages/backups:/backups
  #   env_file: .env
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "600m"
  #       max-file: "5"
  #       # compress: "true"

  caddy:
    depends_on:
      - django-a
      - django-b
    env_file: .env
    command: caddy run --adapter caddyfile --config /etc/caddy/Caddyfile
    image: caddy:2.4.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfiles/caddy/Caddyfile:/etc/caddy/Caddyfile  # configuration
      - /data/djangopackages/caddy/config:/config  # configuration autosaves
      - /data/djangopackages/caddy/data:/data  # saving certificates
      - media:/data/media
      - static:/data/static
    logging:
      driver: "json-file"
      options:
        max-size: "600m"
        max-file: "5"
        # compress: "true"

  redis:
    build: ./dockerfiles/redis
    expose:
      - 6379
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        # compress: "true"
