# Generated by Django 4.0.3 on 2022-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grid", "0002_auto_20180214_0617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="\nLinebreaks are turned into 'br' tags<br />\nUrls are turned into links<br />\nYou can use just 'check', 'yes', 'good' to place a checkmark icon.<br />\nYou can use 'bad', 'negative', 'evil', 'sucks', 'no' to place a negative icon.<br />\nPlus just '+' or '-' signs can be used but cap at 3 multiples to protect layout<br/>\n\n",
                max_length=1000,
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="grid",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Lines are broken and urls are urlized",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
    ]
