# Generated by Django 5.2.9 on 2026-01-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_alter_element_id_alter_feature_id_alter_grid_id_and_more'),
        ('package', '0025_remove_package_commit_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gridpackage',
            constraint=models.UniqueConstraint(fields=('grid', 'package'), name='unique_grid_package'),
        ),
    ]
