# Generated by Django 6.0.4 on 2026-09-17 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_gridpackage_unique_grid_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grid',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Grids created by new accounts stay hidden until approved', verbose_name='Is Approved'),
        ),
    ]
