"""grid url patterns"""

from django.urls import path, re_path

from grid.views import (
    AddGridView,
    AjaxGridSearchView,
    EditGridView,
    GridListView,
    AddFeatureView,
    AddGridPackageView,
    AjaxPackageSearchView,
    GridOpenGraphView,
    add_new_grid_package,
    DeleteFeatureView,
    DeleteGridPackageView,
    EditElementView,
    EditFeatureView,
    grid_detail,
    GridTimesheetView,
    grid_detail_landscape,
)
from package.views import PackageByGridListView

urlpatterns = [
    path(
        "add/",
        view=AddGridView.as_view(),
        name="add_grid",
    ),
    path(
        "<slug:slug>/edit/",
        view=EditGridView.as_view(),
        name="edit_grid",
    ),
    path(
        "element/<int:feature_id>/<int:package_id>/",
        view=EditElementView.as_view(),
        name="edit_element",
    ),
    re_path(
        r"^feature/add/(?P<grid_slug>[a-z0-9\-\_]+)/$",
        view=AddFeatureView.as_view(),
        name="add_feature",
    ),
    path(
        "feature/<int:id>/",
        view=EditFeatureView.as_view(),
        name="edit_feature",
    ),
    path(
        "feature/<int:id>/delete/",
        view=DeleteFeatureView.as_view(),
        name="delete_feature",
    ),
    path(
        "package/<int:id>/delete/",
        view=DeleteGridPackageView.as_view(),
        name="delete_grid_package",
    ),
    re_path(
        r"^(?P<grid_slug>[a-z0-9\-\_]+)/package/add/$",
        view=AddGridPackageView.as_view(),
        name="add_grid_package",
    ),
    re_path(
        r"^(?P<grid_slug>[a-z0-9\-\_]+)/package/add/new$",
        view=add_new_grid_package,
        name="add_new_grid_package",
    ),
    path(
        "ajax_package_search/",
        view=AjaxPackageSearchView.as_view(),
        name="ajax_package_search",
    ),
    path(
        "ajax_grid_search/",
        view=AjaxGridSearchView.as_view(),
        name="ajax_grid_search",
    ),
    path(
        "",
        view=GridListView.as_view(),
        name="grids",
    ),
    path(
        "g/<slug:slug>/",
        view=grid_detail,
        name="grid",
    ),
    path(
        "g/<slug:slug>/opengraph/",
        view=GridOpenGraphView.as_view(),
        name="grid_opengraph",
    ),
    path(
        "g/<slug:slug>/landscape/",
        view=grid_detail_landscape,
        name="grid_landscape",
    ),
    path(
        "g/<slug:slug>/timesheet/",
        view=GridTimesheetView.as_view(),
        name="grid_timesheet",
    ),
    path(
        "g/<slug:slug>/packages/",
        view=PackageByGridListView.as_view(),
        name="grid_packages",
    ),
]
