# Generated by Django 4.0.2 on 2022-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180214_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='body_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='PSA Body Text'),
        ),
    ]
