# Generated by Django 4.0.2 on 2022-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_psa_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='body_text',
            field=models.TextField(blank=True, null=True, verbose_name='PSA Body Text'),
        ),
    ]
