# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields

from searchv2.models import PACKAGE_TYPE


def migrate_item_pk(apps, schema_editor):
    # add item_pk to current search records
    SearchV2 = apps.get_model('searchv2', 'SearchV2')
    Package = apps.get_model('package', 'Package')
    Grid = apps.get_model('grid', 'Grid')
    for search in SearchV2.objects.iterator():
        model = Package if search.item_type == PACKAGE_TYPE else Grid
        try:
            item = model.objects.get(slug=search.slug)
        except model.DoesNotExist:
            continue
        else:
            search.item_pk = item.pk
            search.save()


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0002_auto_20150716_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchv2',
            name='item_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Item primary key'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='absolute_url',
            field=models.CharField(max_length=255, verbose_name='Absolute URL'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='clean_title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Clean title with no crud'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='title_no_prefix',
            field=models.CharField(db_index=True, max_length=100, verbose_name='No Prefix Title'),
        ),
        migrations.RunPython(migrate_item_pk),
        # make item_pk field required
        migrations.AlterField(
            model_name='searchv2',
            name='item_pk',
            field=models.PositiveIntegerField(verbose_name='Item primary key'),
        ),
    ]
