# Generated by Django 4.0.2 on 2022-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0003_auto_20180214_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchv2',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Repo Description'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='participants',
            field=models.TextField(blank=True, help_text='List of collaborats/participants on the project', max_length=500, verbose_name='Participants'),
        ),
    ]
