# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0003_auto_20171130_1335'),
        ('searchv2', '0003_auto_20180214_0617'),
    ]

    operations = [
    ]
