# Generated by Django 5.1.4 on 2025-01-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0004_alter_searchv2_pypi_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchv2',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
