# Generated by Django 4.0.2 on 2022-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0004_alter_searchv2_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchv2',
            name='description',
            field=models.TextField(blank=True, verbose_name='Repo Description'),
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='participants',
            field=models.TextField(blank=True, help_text='List of collaborats/participants on the project', verbose_name='Participants'),
        ),
    ]
