# Generated by Django 5.2.12 on 2026-03-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0005_searchv2_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchV2',
        ),
    ]
