from django.urls import path, re_path
from django.views.decorators.cache import cache_page

from package.views import (
    LatestPackageListView,
    MostLikedPackageListView,
    PackageOpenGraphDetailView,
    PackageExampleCreateView,
    AddPackageView,
    PackageUsageToggleView,
    ValidateRepositoryURLView,
    PackageExampleDeleteView,
    PackageDocumentationUpdateView,
    PackageExampleUpdateView,
    PackageUpdateView,
    PackageFlagApproveView,
    PackageFlagView,
    PackageFlagRemoveView,
    GitHubWebhookView,
    PackageRulesView,
    PackageFetchDataView,
    PackageVersionListView,
    PackageDetailView,
    PackageListView,
)

urlpatterns = [
    path(
        "",
        view=PackageListView.as_view(),
        name="packages",
    ),
    path(
        "latest/",
        LatestPackageListView.as_view(),
        name="latest_packages",
    ),
    path(
        "liked/",
        MostLikedPackageListView.as_view(),
        name="liked_packages",
    ),
    path(
        "add/",
        view=AddPackageView.as_view(),
        name="add_package",
    ),
    path(
        "add/validate/",
        view=ValidateRepositoryURLView.as_view(),
        name="validate_repo_url",
    ),
    path(
        "<slug:slug>/edit/",
        view=PackageUpdateView.as_view(),
        name="edit_package",
    ),
    path(
        "<slug:slug>/fetch-data/",
        view=PackageFetchDataView.as_view(),
        name="fetch_package_data",
    ),
    path(
        "<slug:slug>/example/add/",
        view=PackageExampleCreateView.as_view(),
        name="add_example",
    ),
    path(
        "<slug:slug>/example/<int:id>/edit/",
        view=PackageExampleUpdateView.as_view(),
        name="edit_example",
    ),
    path(
        "<slug:slug>/example/<int:id>/delete/",
        view=PackageExampleDeleteView.as_view(),
        name="delete_example",
    ),
    path(
        "<slug:slug>/flag/",
        view=PackageFlagView.as_view(),
        name="flag",
    ),
    path(
        "flag/<int:pk>/approve/",
        view=PackageFlagApproveView.as_view(),
        name="flag_approve",
    ),
    path(
        "flag/<int:pk>/remove/",
        view=PackageFlagRemoveView.as_view(),
        name="flag_remove",
    ),
    path(
        "p/<slug:slug>/opengraph/",
        view=cache_page(60 * 60 * 24)(PackageOpenGraphDetailView.as_view()),
        name="package_opengraph",
    ),
    path(
        "p/<slug:slug>/rules/",
        view=PackageRulesView.as_view(),
        name="package_rules",
    ),
    path(
        "p/<slug:slug>/",
        view=PackageDetailView.as_view(),
        name="package",
    ),
    re_path(
        r"^usage/(?P<slug>[-\w]+)/(?P<action>add|remove)/$",
        view=PackageUsageToggleView.as_view(),
        name="usage",
    ),
    path(
        "<slug:slug>/documentation/edit/",
        view=PackageDocumentationUpdateView.as_view(),
        name="edit_documentation",
    ),
    path("github-webhook/", view=GitHubWebhookView.as_view(), name="github_webhook"),
    path(
        "<slug:slug>/versions/",
        view=PackageVersionListView.as_view(),
        name="package_versions",
    ),
]
