name: Deploy latest main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Publish Production Docker Image
    runs-on: ubuntu-latest
    if: github.repository_owner == 'djangopackages'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Install bumpver
        run: |
          python -m pip install --upgrade pip
          python -m pip install bumpver

      - name: Configure git to push
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Automated Publisher"

      - name: Bump Version
        run: |
          bumpver update --no-fetch --verbose

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and Push Production Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./dockerfiles/django/Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository }}:latest

      - name: Push Release Build to GitHub
        run: |
          git push
