name: Django Probe

on:
  schedule:
    # Runs monthly on the 1st.
    - cron: "37 14 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  django-probe:
    uses: tim-schilling/django-probe/.github/workflows/django-probe-submit-uv.yml@main
    with:
      path: "."
      python-version: "3.12"
    secrets:
      DJANGO_PROBE_TOKEN: ${{ secrets.DJANGO_PROBE_TOKEN }}
