FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONPATH /code
ENV PYTHONUNBUFFERED 1
ENV PYTHONWARNINGS ignore

# Install System dependencies
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
       gcc \
       build-essential

RUN --mount=type=cache,target=/root/.cache,id=pip \
    python -m pip install --upgrade pip uv

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY requirements.txt /code/requirements.txt

RUN --mount=type=cache,target=/root/.cache,id=pip \
    uv pip install --system --requirement /code/requirements.txt

COPY ./dockerfiles/django/entrypoint.sh /entrypoint.sh
# RUN sed -i 's/\r//' /entrypoint.sh \
#     && chmod +x /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./dockerfiles/django/start-dev.sh /start-dev.sh
# RUN sed -i 's/\r//' /start-dev.sh \
#     && chmod +x /start-dev.sh
RUN chmod +x /start-dev.sh

WORKDIR /code

COPY . /code

# RUN python -m manage tailwind --skip-checks download_cli

RUN DATABASE_URL=sqlite://:memory: SECRET_KEY=build-key REDIS_URL= python manage.py tailwind --skip-checks download_cli

# RUN DATABASE_URL=sqlite://:memory: SECRET_KEY=build-key python manage.py collectstatic --noinput --clear

ENTRYPOINT ["/entrypoint.sh"]
