FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONPATH /code
ENV PYTHONUNBUFFERED 1
ENV PYTHONWARNINGS ignore
ENV UV_LINK_MODE=copy

# Install System dependencies
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
       curl \
       gcc \
       wget \
       build-essential

WORKDIR /code

COPY pyproject.toml uv.lock ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

COPY ./dockerfiles/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh \
    && chmod +x /start-dev.sh

COPY . .

# RUN python -m manage tailwind --skip-checks download_cli

RUN DATABASE_URL=sqlite://:memory: SECRET_KEY=build-key REDIS_URL= uv run manage.py tailwind --skip-checks download_cli

# RUN DATABASE_URL=sqlite://:memory: SECRET_KEY=build-key python manage.py collectstatic --noinput --clear
