# Generated by Django 5.2.11 on 2026-02-16 09:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django_extensions.db.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("pg_trgm"),
        migrations.CreateModel(
            name="SearchV3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("weight", models.IntegerField(default=0, verbose_name="Weight")),
                (
                    "item_type",
                    models.CharField(
                        choices=[("package", "Package"), ("grid", "Grid")],
                        max_length=40,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Title"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Repo Description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Category"
                    ),
                ),
                ("repo_watchers", models.IntegerField(default=0, verbose_name="Stars")),
                (
                    "repo_forks",
                    models.IntegerField(default=0, verbose_name="repo forks"),
                ),
                (
                    "pypi_downloads",
                    models.IntegerField(default=0, verbose_name="PyPI downloads"),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Score")),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.CombinedSearchVector(
                                        django.contrib.postgres.search.SearchVector(
                                            "title", config="english", weight="A"
                                        ),
                                        "||",
                                        django.contrib.postgres.search.SearchVector(
                                            "slug", config="english", weight="B"
                                        ),
                                        django.contrib.postgres.search.SearchConfig(
                                            "english"
                                        ),
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "description", config="english", weight="C"
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        "english"
                                    ),
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "category", config="english", weight="D"
                                ),
                                django.contrib.postgres.search.SearchConfig("english"),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "participants", config="english", weight="D"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "usage",
                    models.IntegerField(default=0, verbose_name="Number of users"),
                ),
                (
                    "participants",
                    models.TextField(
                        blank=True,
                        help_text="List of collaborators/participants on the project",
                        verbose_name="Participants",
                    ),
                ),
                (
                    "last_committed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last commit"
                    ),
                ),
                (
                    "last_released",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last release"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SearchV3s",
                "ordering": ["-weight"],
                "indexes": [
                    models.Index(
                        fields=["item_type", "slug"], name="searchv3_item_slug"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="searchv3_vec_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title"],
                        name="searchv3_title_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["slug"],
                        name="searchv3_slug_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
    ]
